In [3]:
# NumPy Array Indexin
import numpy as np 

arr = np.array([1,2,3,4,5])
print(arr[2]) # accessing value by index

# Get third and fifth elements from the following array and add them.
print(arr[2] + arr[4])

3
8


In [7]:
# Access 2-D Arrays values
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 2]) # 1st row 3rd element
print(arr[1, 3]) # 2nd row 4th element

3
9


In [10]:
# Access 3-D Arrays values
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


In [11]:
# Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1]) # access last element from the 2nd dim

10
