In [1]:
# Data Types in Python
# By default Python have these data types:
# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

import numpy as np


In [4]:
# Checking the Data Type of an Array
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)
arr2 = np.array(['apple', 'banana', 'cherry'])
print(arr2.dtype)

int64
<U6


In [5]:
# We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [10]:
# For i, u, f, S and U we can define size as well.

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [12]:
# What if a Value Can Not Be Converted?
# If a type is given in which elements can't be casted then NumPy will raise a ValueError.
# A non integer string like 'a' can not be converted to integer (will raise an error):
# arr = np.array(['a', '2', '3'], dtype='i') # ValueError: invalid literal for int() with base 10: 'a'


In [14]:
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
# newarr = arr.astype(int) # also can use int
print(newarr)
print(newarr.dtype)

arr = np.array([1,2,3,4])
newarr = arr.astype('f')
print(newarr)
print(newarr.dtype)



[1 2 3]
int32
[1. 2. 3. 4.]
float32


In [15]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [17]:
# The Difference Between Copy and View
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# Make a copy, change the original array, and display both arrays:
# The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[1] = 50
print(arr)
print(x)



[ 1 50  3  4  5]
[1 2 3 4 5]


In [18]:
# Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[1] = 50

print(arr)
print(x)

[ 1 50  3  4  5]
[ 1 50  3  4  5]


In [20]:
# Check if Array Owns its Data
# As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x)
print(y)
print(x.base) # None
print(y.base) # [1 2 3 4 5]

[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]
