In [4]:
# NumPy offers the random module to work with random numbers.

import numpy as np

# The random module's rand() method returns a random float between 0 and 1.

arr = np.random.rand(4) # Generate a random float from 0 to 1:
print(arr)

[0.0260572  0.952423   0.34993313 0.13228616]


In [3]:
# The random module's rand() method returns a random float between 0 and 1.
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
arr2 = np.random.rand(3,5)
print(arr2)

[[0.52659808 0.99640679 0.23012003 0.97839798 0.23021794]
 [0.00210265 0.63576954 0.39177349 0.96245766 0.7510069 ]
 [0.42249858 0.39200793 0.00716006 0.18169521 0.14790335]]


In [5]:
# The random module's rand() method returns a random float between -1 and 1.
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
arr3 = np.random.randn(3,5)
print(arr3)

[[-1.73306682 -1.2478307  -0.90281433  0.38391553  1.02446836]
 [-0.91527936 -1.09417409 -0.73071771 -1.07687751 -0.64847255]
 [-1.5108347   0.7598646  -1.06131081 -0.83086171 -0.93294502]]


In [6]:
arr4 = np.random.ranf(4)
print(arr4)

[0.95591236 0.64432869 0.21414193 0.68745937]


In [9]:
arr5 = np.random.randint(10, 100, 5) # (min value, max value, total value)
print(arr5)

[89 92 96 37 80]


In [12]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
x=np.random.randint(100, size=(5))
print(x)

[83 74 40 79 46]


In [15]:
# Array filled with 0
arr_zero = np.zeros(4)
arr_zero_1 = np.zeros((3,4))
print(arr_zero)
print()
print(arr_zero_1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
# Array filled with 1
arr_one = np.ones(4)
arr_one_1 = np.ones((3,4))
print(arr_one)
print()
print(arr_one_1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
# create an enpty array
arr_epmty = np.empty(4)
print(arr_epmty)

[0. 0. 0. 0.]


In [21]:
# array with range of elements
arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


In [27]:
# array diagonal element filled with 1
# arr_diag = np.eye(3)
arr_diag = np.eye(4,5)
print(arr_diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [28]:
# create an array with values that are spaced linearly in a specified interval
arr_lin = np.linspace(1,10, num=5)
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]
