In [1]:
# Iterating Arrays
# Iterating means going through elements one by one.
# As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
# If we iterate on a 1-D array it will go through each element one by one.
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [3]:
# Iterating 2-D Arrays
# In a 2-D array it will go through all the rows.
# If we iterate on a n-D array it will go through n-1th dimension one by one.
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x) #return array
    
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [7]:
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x) #return 2d array
    
for x in arr:
    for y in x:
        print(y) #return 1d array
        
for x in arr:
    for y in x:
        for z in y:
            print(z) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
# It solves some basic issues which we face in iteration, lets go through it with examples.

# Iterating on Each Scalar Element
# In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

# Iterate through the following 3-D array:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [14]:
# Iterating Array With Different Data Types
# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, 
# that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)
    
# Iterating With Different Step Size
# We can use filtering and followed by iteration.
# Iterate through every scalar element of the 2D array skipping 1 element:
for x in np.nditer(arr[:, ::2]):
    print(x)
    
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.
# Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.
for idx, x in np.ndenumerate(arr):
    print(idx, x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
1
3
5
7
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
