In [ ]:
# Searching Arrays
# You can search an array for a certain value, and return the indexes that get a match.
# To search an array, use the where() method.
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4) # Find the indexes where the value is 4:
print(x)

(array([3, 5, 6]),)


In [6]:
# Find the indexes where the values are even:
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 6]),)


In [7]:
# The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.
# Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [8]:
# Search From the Right Side
# By default the left most index is returned, but we can give side='right' to return the right most index instead.
# Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side="right")
print(x)

2


In [9]:
# Multiple Values
# To search for more than one value, use an array with the specified values.
# Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [11]:
# Sorting Arrays
# Sorting means putting elements in an ordered sequence.
# Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
# The NumPy ndarray object has a function called sort(), that will sort a specified array.
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]
