In [1]:
# You could use arithmetic operators + - * / directly between NumPy arrays, 
# but this section discusses an extension of the same where we have functions that can take any array 
# like objects e.g. lists, tuples etc. and perform arithmetic conditionally.
# Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.
import numpy as np

In [2]:
var = np.array([1,2,3,4])
addvar = var + 5
print(addvar)

[6 7 8 9]


In [15]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1 + var2) # direct addation
print(np.add(var1, var2)) # add()

print(var1 - 2)
print(np.subtract(var1, 2)) # subtract()
print(var1 * 2)
print(np.multiply(var1, 2)) # add()
print(var1 / 2)
print(np.divide(var1, 2)) # add()
print(var1 % 2)
print(np.mod(var1, 2)) # add()
print(np.power(var1, 2)) # add()
print(np.reciprocal(var1)) # add()

[2 4 6 8]
[2 4 6 8]
[-1  0  1  2]
[-1  0  1  2]
[2 4 6 8]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0.5 1.  1.5 2. ]
[1 0 1 0]
[1 0 1 0]
[ 1  4  9 16]
[1 0 0 0]


In [14]:
var3 = np.array([[1,2,3,4], [4,5,6,7]])
var4 = np.array([[1,2,3,4], [4,5,6,7]])
print(np.add(var3, var4))


[[ 2  4  6  8]
 [ 8 10 12 14]]


In [17]:
Absolute Values
# Both the absolute() and the abs() functions functions do the same absolute operation element-wise 
# but we should use absolute() to avoid confusion with python's inbuilt math.abs()
arr = np.array([-1, -2, 1, 2, 3, -4])
print(np.absolute(arr))

[1 2 1 2 3 4]


In [27]:
# Arithmetic Functions
var = np.array([4,2,5,8,7,9,1,3])
print(np.min(var), np.argmin(var))
print(np.max(var), np.argmax(var))
print(np.sqrt(var))

1 6
9 5
[2.         1.41421356 2.23606798 2.82842712 2.64575131 3.
 1.         1.73205081]


In [28]:
var = np.array([[4,2,5,8], [7,9,1,3]])
# axis 0 = column
print(np.min(var, axis=0)) 
print(np.max(var, axis=0))
# axis 1 = row
print(np.min(var, axis=1)) 
print(np.max(var, axis=1))

print(np.sqrt(var)) # square root

[4 2 1 3]
[7 9 5 8]
[2 1]
[8 9]
[[2.         1.41421356 2.23606798 2.82842712]
 [2.64575131 3.         1.         1.73205081]]


In [31]:
print(np.sin(var))
print()
print(np.cos(var))

[[-0.7568025   0.90929743 -0.95892427  0.98935825]
 [ 0.6569866   0.41211849  0.84147098  0.14112001]]

[[-0.65364362 -0.41614684  0.28366219 -0.14550003]
 [ 0.75390225 -0.91113026  0.54030231 -0.9899925 ]]


In [32]:
var = np.array([4,2,5,8,7,9,1,3])
print(np.cumsum(var)) # qumulative sum (sum bebore value)

[ 4  6 11 19 26 35 36 39]
