In [8]:
# NumPy Array Slicing
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[2:5]) # Slice elements from index 2 to index 4
print(arr[3:]) # Slice elements from index 3 to the end of the array
print(arr[:5]) # Slice elements from the beginning to index 4, (5 not included):

# Negative Slicing
print(arr[-3:-1]) # Slice from the index 3 from the end to index 1 from the end, (-1 not included):

# STEP
print(arr[1:6:2]) # Return every other element from index 1 to index 6:
print(arr[::2]) # Return every other element from the entire array:


[3 4 5]
[4 5 6 7]
[1 2 3 4 5]
[5 6]
[2 4 6]
[1 3 5 7]


In [13]:
# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included):

print(arr[0:2, 2]) # From both elements, return index 2:

# arr[row number, column number]
print(arr[0:2, 1:4]) # From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:


[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
